# Generated by Django 5.2.8 on 2025-12-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Businesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='businesses/')),
                ('description', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
