# Generated by Django 5.2.8 on 2025-12-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesfloor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesses',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
