# Generated by Django 5.2.8 on 2025-12-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesfloor', '0002_businesses_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesses',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
