# Generated by Django 5.2.8 on 2025-12-24 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesfloor', '0003_alter_businesses_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesses',
            name='rating',
        ),
    ]
