# Generated by Django 5.2.8 on 2025-12-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesfloor', '0004_remove_businesses_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesses',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
