# Generated by Django 5.2.8 on 2025-12-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesfloor', '0005_businesses_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesses',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
