# Generated by Django 5.2.8 on 2026-01-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesfloor', '0006_alter_businesses_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesses',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
