# Generated by Django 5.2.8 on 2026-01-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesfloor', '0007_alter_businesses_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesses',
            name='ratingNumber',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
