# Generated by Django 5.2.8 on 2026-01-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesfloor', '0009_favorites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='favorites',
            new_name='userFavoritesBusiness',
        ),
    ]
