# Generated by Django 5.2.8 on 2026-03-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesfloor', '0010_rename_favorites_userfavoritesbusiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesses',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
