# Generated by Django 5.2.7 on 2025-10-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_members_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
